//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestXafSolution2.Module.TestWork2
{

    public partial class Cargo : XPLiteObject
    {
        int fNumber;
        [Key(true)]
        [Browsable(false)]
        public int Number
        {
            get { return fNumber; }
            set { SetPropertyValue<int>("Number", ref fNumber, value); }
        }
        string fName;
        [Size(20)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Area fNumber_Area;
        [Association(@"CargoReferencesArea")]
        public Area Number_Area
        {
            get { return fNumber_Area; }
            set { SetPropertyValue<Area>("Number_Area", ref fNumber_Area, value); }
        }
        int fWeight;
        [DevExpress.Persistent.Validation.RuleRange("", DevExpress.Persistent.Validation.DefaultContexts.Save, 1, 10000)]
        public int Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<int>("Weight", ref fWeight, value); }
        }
        DateTime fCreate_Cargo;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0: ddd, dd MMMM yyyy hh:mm:ss tt}"), DevExpress.ExpressApp.Model.ModelDefault("EditMask", "ddd, dd MMMM yyyy hh:mm:ss tt"), DevExpress.ExpressApp.Model.ModelDefault("PropertyEditorType", "WinSolution.Module.Win.MyDatePropertyEditor")]
        public DateTime Create_Cargo
        {
            get { return fCreate_Cargo; }
            set { SetPropertyValue<DateTime>("Create_Cargo", ref fCreate_Cargo, value); }
        }
        DateTime fDelete_Cargo;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0: ddd, dd MMMM yyyy hh:mm:ss tt}"), DevExpress.ExpressApp.Model.ModelDefault("EditMask", "ddd, dd MMMM yyyy hh:mm:ss tt"), DevExpress.ExpressApp.Model.ModelDefault("PropertyEditorType", "WinSolution.Module.Win.MyDatePropertyEditor")]
        public DateTime Delete_Cargo
        {
            get { return fDelete_Cargo; }
            set { SetPropertyValue<DateTime>("Delete_Cargo", ref fDelete_Cargo, value); }
        }
        string fNameDelStore;
        [Size(200)]
        public string NameDelStore
        {
            get { return fNameDelStore; }
            set { SetPropertyValue<string>("NameDelStore", ref fNameDelStore, value); }
        }
    }

}
